name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.Cwyb4sb9GRuZcqlfVjk0L5pS }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_0Pm3Mb5u8O7Xjt2Irt2Lunx6gowG }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.T0ASDWX5Cdavi33T7f11QTtw }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.T0ASDWX5Cdavi33T7f11QTtw }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.T0ASDWX5Cdavi33T7f11QTtw }}
