name: Vercel Run Test 
on:
  push:
    branches:
      - main
jobs:
  Run_Test:
    runs-on: ubuntu-latest
    name: Run_Test
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint